# WARNING: This file is generated by https://json2pyi.pages.dev/#TypedDictClass and subject to change.
# Do not edit this file manually.

from __future__ import annotations

from typing import Any, TypedDict


class YTDLOutput(TypedDict):
    id: str
    title: str
    description: str
    duration: int
    timestamp: int
    creators: list[str]
    channel: str
    uploader: str
    uploader_id: str
    view_count: int
    like_count: int
    repost_count: int
    comment_count: int
    track: str
    artists: list[str]
    channel_id: str
    uploader_url: str
    formats: list[Format]
    thumbnails: list[Thumbnail]
    http_headers: Any
    original_url: str
    webpage_url: str
    webpage_url_basename: str
    webpage_url_domain: str
    extractor: str
    extractor_key: str
    playlist: None
    playlist_index: None
    thumbnail: str
    display_id: str
    fulltitle: str
    duration_string: str
    upload_date: str
    release_year: None
    artist: str
    creator: str
    requested_subtitles: None
    _has_drm: None
    epoch: int
    format_id: str
    url: str
    ext: str
    width: int
    height: int
    protocol: str
    resolution: str
    dynamic_range: str
    aspect_ratio: float
    cookies: str
    video_ext: str
    audio_ext: str
    vbr: None
    abr: None
    tbr: None
    format: str


class Format(TypedDict):
    format_id: str
    url: str
    ext: str
    width: int
    height: int
    protocol: str
    resolution: str
    dynamic_range: str
    aspect_ratio: float
    cookies: str
    http_headers: Any
    video_ext: str
    audio_ext: str
    vbr: None
    abr: None
    tbr: None
    format: str


class Thumbnail(TypedDict):
    url: str
    width: int
    height: int
    id: str
    resolution: str
